### ISSUE TITLE
SW doesn't work in Firefox when history is off

### ISSUE THREAD

**Issue by felixsanz** [mdn/sw-test#16]
I didn't find a better place to ask this, but why service workers doesn't work in Firefox if i have history disabled?

**Comment by mireille-raad** [comment]
Ha! I just tested it as well. It still doesn't work when:
- history is off
- when I have selected `Delete cookies and site data when Firefox is closed` (unless I add localhost to exception list)

It could be worth to have a PR to update the content on:
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#why_is_my_service_worker_failing_to_register

I open an issue there: https://github.com/mdn/content/issues/9679

**Comment by schalkneethling** [comment]
As this is being tracked in the `content` repo, I am going to go ahead and close this one. Thank you everyone.
