### ISSUE TITLE
Why cloning the response in sw-test/sw.js?

### ISSUE THREAD

**Issue by sp00m** [mdn/sw-test#21]
This isn't a real issue but more a question about your service worker: why would you need to clone the response on [line 28](https://github.com/mdn/sw-test/blob/gh-pages/sw.js#L28)? I would have written it like this:

```js
.then(function(response) {
	caches.open('v1').then(function(cache) {
		cache.put(event.request, response);
	});
	return response;
})
```

Any thoughts about this?

**Comment by chrisdavidmills** [comment]
This is because you are already putting the response object into the cache on line 26. You therefore need to return a clone of the response for it to work.
