### ISSUE TITLE
Failed to register a ServiceWorker Issue

### ISSUE THREAD

**Issue by Jaysonvdw** [mdn/sw-test#24]
Hello, keep getting the following in the console, even after deploying to https and enabling experimental web platform features: Registration failed with TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

Here is the site: https://jaysonvdw.github.io/

Please assist

**Comment by chrisdavidmills** [comment]
Hi!

Your problem is in the line

navigator.serviceWorker.register('/sw-test/sw.js', { scope: '/sw-test/' }).then(function(reg) {

You have your sw.js file in the root of the site, not in a sw-test subfolder, so this line should be

navigator.serviceWorker.register('sw.js', { scope: '/' }).then(function(reg) {

I think, or you could just remove the

, { scope: '/sw-test/' }

bit altogether.

This is from memory; if I got it wrong let me know and I'll explore it more deeply ;-)

**Comment by Jaysonvdw** [comment]
Hi Chris,

Wow, that was a quick response, thanks, I appreciate the feedback.

So that seemed to have worked a treat! but I've been seeing 'Service worker installing' now for about 10 minutes (no other errors) and the site is not currently available offline (I should see 'active' at some point, correct?)

I did deploy to Surge this time however, not sure if that makes a difference...

https://colorful-note.surge.sh/

**Comment by chrisdavidmills** [comment]
Ah ha - try refreshing the page, and you should see it active. Idea being that the SW can't become active the first time the page is loaded, but it then starts to work when the setup has been done the first time around.

**Comment by Jaysonvdw** [comment]
Yip, that worked like a dream! Turns out I forgot to edit the referencing for caching in the sw file as well.

What do I do with this line if I want to use the repo for other projects?

 return caches.match('/gallery/myLittleVader.jpg');

**Comment by chrisdavidmills** [comment]
So the URL in there needs to be relative to the base URL.

On your site, that image is at "https://jaysonvdw.github.io/gallery/myLittleVader.jpg", so the URL referred to is "/gallery/myLittleVader.jpg"

You just need to respect that same pattern.

**Comment by Jaysonvdw** [comment]
Right, ok. 

Thanks very much for the assistance Chris, much appreciated.

**Comment by chrisdavidmills** [comment]
You are welcome, any time.

**Comment by db325** [comment]
my service worker isn't registering at all. i'm not getting an errors or anything. my registration looks like this=>  

 if(navigator.serviceWorker){
    console.log("Will the service worker register?");
    navigator.serviceWorker.register('/sw.js')
      .then(function(reg){
        console.log("Yes, it did.");
      }).catch(function(err) {
        console.log("No it didn't. This happened: ", err)
      });
}

when i remove the if statement, i get an error that says can not read property register of undefined...

**Comment by chrisdavidmills** [comment]
@db325 Hrm, I don't know what the problem is just from looking at this. First of all, what does your directory structure look like? I am wondering if you have the SW file in the wrong place.

I tend to use `if('serviceWorker' in navigator) {` to test for SWs, not sure if that would make a difference. 

What browser are you using?

**Comment by Inforcekid** [comment]
This is what i did in the app.js and` it worked.

```
if ('serviceWorker' in navigator){
  navigator.serviceWorker.register('/sw.js').then(function(registration){
    console.log('service worker registration succeeded:',registration);
  },
function(error){
  console.log('service worker registration failed:',error);
});
}
else{
  console.log('service workers are not supported.');
}
```

**Comment by chrisdavidmills** [comment]
Yup, looks OK to me.

**Comment by NaumanMoazzam** [comment]
@chrisdavidmills Hi,

I have added the condition you mention` 'if('serviceWorker' in navigator)`

Additionally, What I have done is: 
Used React, '`run npm build`' and deployed on local server i.e. XAMPP. 

Still can't go through this error message.

```
FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost/firebase-cloud-messaging-push-scope') with script ('http://localhost/firebase-messaging-sw.js'): A bad HTTP response code (404) was received when fetching the script. (messaging/failed-service-worker-registration).
    at t.<anonymous> (http://localhost/build/static/js/2.c1bc5503.chunk.js:2:868974)
    at http://localhost/build/static/js/2.c1bc5503.chunk.js:2:3710
    at Object.throw (http://localhost/build/static/js/2.c1bc5503.chunk.js:2:3815)
    at s (http://localhost/build/static/js/2.c1bc5503.chunk.js:2:2604)
```

**Comment by AiTranXuan** [comment]
> @chrisdavidmills Hi,
> 
> I have added the condition you mention` 'if('serviceWorker' in navigator)`
> 
> Additionally, What I have done is:
> Used React, '`run npm build`' and deployed on local server i.e. XAMPP.
> 
> Still can't go through this error message.
> 
> ```
> FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost/firebase-cloud-messaging-push-scope') with script ('http://localhost/firebase-messaging-sw.js'): A bad HTTP response code (404) was received when fetching the script. (messaging/failed-service-worker-registration).
>     at t.<anonymous> (http://localhost/build/static/js/2.c1bc5503.chunk.js:2:868974)
>     at http://localhost/build/static/js/2.c1bc5503.chunk.js:2:3710
>     at Object.throw (http://localhost/build/static/js/2.c1bc5503.chunk.js:2:3815)
>     at s (http://localhost/build/static/js/2.c1bc5503.chunk.js:2:2604)
> ```

same me

**Comment by anwarsaadat** [comment]
I have problem while using service worker in next.js, I have configured a production server in node, it still does not working, here is the code.

componentDidMount() {
    if ("serviceWorker" in navigator) {
      navigator.serviceWorker
        // 'sw.js', { scope: '/' }
        .register("/service-worker.js")
        .then((registration) => {
          console.log("service worker registration successful", registration);
        })
        .catch((err) => {
          console.log("service worker registration failed", err.message);
        });
    }
  }


app.prepare().then(() => {
  http
    .createServer((req, res) => {
      const parsedUrl = url.parse(req.url, true);
      const { pathname } = parsedUrl;

      if (pathname === "/service-worker.js") {
        const filePath = path.join(__dirname, ".next", pathname);
        app.serveStatic(req, res, filePath);
      } else {
        handle(req, res, parsedUrl);
      }
    })
    .listen(port, () => {
      console.log(`Listening on PORT ${port}`);
    });
});

module.exports = {
  webpack: (config) => {
    config.plugins.push(
      new SWPrecacheWebpackPlugin({
        cacheId: "jiroy",
        minify: true,
        staticFileGlobsIgnorePatterns: [/\.next\//],
        runtimeCaching: [
          {
            handler: "networkFirst",
            urlPattern: /^https?.*/,
          },
        ],
      })
    );

    return config;
  },
};

**Comment by SebasProgrammer2021** [comment]
hello guys, can u help me i have the same issue
![image](https://user-images.githubusercontent.com/91297621/138120639-18574ca4-871b-4ac1-bb43-130b30905f6d.png)

could u help me please!
I have been reviewing the route and it was working fine i dont know why it crashed

**Comment by Vaisakhkm2625** [comment]
> Hello, keep getting the following in the console, even after deploying to https and enabling experimental web platform features: Registration failed with TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
> 
> Here is the site: https://jaysonvdw.github.io/
> 
> Please assist

did you resolved it?, 
I am trying to learn PWAs with  https://www.freecodecamp.org/news/build-a-pwa-from-scratch-with-html-css-and-javascript/

I realized that it need to be hosted somewhere, so i just put it in github, and opened in github pages...
But I also got the same error(https://vaisakhkm2625.github.io/pwatry/).

I though you resolve it (https://jaysonvdw.github.io/), but no, you have same error, any idea what is happing there...

Can anyone help me please, I am just a beginner...
