### ISSUE TITLE
Why return a `caches.match` when failed to fetch?

### ISSUE THREAD

**Issue by trungdq88** [mdn/sw-test#25]
I don't understand this line:
![image](https://user-images.githubusercontent.com/4214509/33522151-ff46bb48-d817-11e7-8409-256bc0fd845e.png)

from here: https://github.com/mdn/sw-test/blob/gh-pages/sw.js#L37

Can someone help me out?

**Comment by chrisdavidmills** [comment]
Hi there @trungdq88 ,

This is a fallback if the network is not available and a fetch attempt is made on an image that can't be fetched. If that is the case, this image will be served instead, which we cache when the service worker is first installed.

It's a bit trivial, but at least illustrates a fallback concept.
