### ISSUE TITLE
localhost

### ISSUE THREAD

**Issue by sixindustries** [mdn/sw-test#33]
OS: Linux Fedora
Chrome: Version 75.0.3770.100 (Official Build) (64-bit)
Python 2

Ran...
python -m SimpleHTTPServer 8001
chrome: http://localhost:8001/sw-test/

Didn't work.  

I removed the "/sw-test/" from the URL and it at least loaded the demo.
Still got 404 error for the service worker.

In app.js I edited line 4 to remove /sw-test/ from the URI and then the slashes from 'scope'.
` navigator.serviceWorker.register('sw.js', { scope: 'sw-test' }).then(function (reg) {`

In sw.js I edited lines 5 - 12 to remove the '/sw-test/':
`        'index.html',
        'style.css',
        'app.js',
        'image-list.js',
        'star-wars-logo.jpg',
        'gallery/bountyHunters.jpg',
        'gallery/myLittleVader.jpg',
        'gallery/snowTroopers.jpg'`

After those edits it worked.

**Comment by chrisdavidmills** [comment]
This is basically what I'd expect to happen. The pathways have to be relative to the domain root, so as is, it would expect to find the index file at `server-path/sw-test/`, not `server-path/`. However, the README instructions weren't very clear on this, so I've improved them.
