### ISSUE TITLE
Server Worker fails to register if the web server has "ForceType: text/html"

### ISSUE THREAD

**Issue by rkhegde** [mdn/sw-test#34]
Hi All,
    Not sure what is the issue here. The SN registration is failing with the below message

"Registration failed with SecurityError: Failed to register a ServiceWorker for scope ('https://www.ctx.com/sw-test/') with script ('https://www.ctx.com/sw-test/sw.js'): The script has an unsupported MIME type ('text/html')."

Has anyone  encountered the above message or has some clue on this?

**Comment by rkhegde** [comment]
Solved this. The apache server i was using had an option in the config file. The option is "ForceType text/html". After removing this, it worked. However i see "Service worker installing" now. If i refresh it shows "Service worker active". But i don't see this behavior when accessing "https://mdn.github.io/sw-test/". Does anyone have more clue on this?

**Comment by ilatypov** [comment]
Could you change the title to reflect the issue with the application at mdn.github.io?  Since this is a sample application, it should be a no-brainer (but seems a brainer now).
