### ISSUE TITLE
python -m http.server leads to a SecurityError due to bad content types

### ISSUE THREAD

**Issue by aokasumi** [mdn/sw-test#35]
Using `python -m http.server 8001` with Python 3.7 on Windows 10 to start a simple server as described will result in the following message printed on to the console in Firefox 74.0:
`Registration failed with SecurityError: The operation is insecure.`

Using Chrome, you can get the following additional information: 
`Registration failed with SecurityError: Failed to register a ServiceWorker for scope ('http://localhost:8001/sw-test/') with script ('http://localhost:8001/sw-test/sw.js'): The script has an unsupported MIME type ('text/plain').`

**It seems like the Python `http.server` module is unable to use the correct mimetypes in the HTTP response for JavaScript files.** Also, the content types of the other JavaScript files are `text/plain` as well in the HTTP response, as for example in the response of app.js:

```
HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/3.7.4
Date: Thu, 19 Mar 2020 19:27:39 GMT
Content-type: text/plain
Content-Length: 2143
Last-Modified: Thu, 19 Mar 2020 19:24:15 GMT
```

The content types of the JPEG images seem to be okay.

If you experience the same problem, starting a server using the Python script at <https://gist.github.com/HaiyangXu/ec88cbdce3cdbac7b8d5> works for me.

**Comment by qiufeihong2018** [comment]
Can you  use 'python -m  SimpleHTTPServer  8001'? @aokasumi
