### ISSUE TITLE
Service Worker not Registered

### ISSUE THREAD

**Issue by Tello-asd** [mdn/sw-test#36]
Hello, I am getting this error all the time, related to the sw.js. I´m not sure what else I can do:

tello-asd.github.io/:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://tello-asd.github.io/') with script ('https://tello-asd.github.io/sw.js'): ServiceWorker script evaluation failed

Here is my web:
https://tello-asd.github.io/

**Comment by chrisdavidmills** [comment]
I'm assuming you fixed this now? The example gives me messages to say the SW registered, then the SW registration succeeded?

**Comment by MESWEB** [comment]
@chrisdavidmills I have this same error. Any change of file location don't fix the problem.
