### ISSUE TITLE
Useless script

### ISSUE THREAD

**Issue by MESWEB** [mdn/sw-test#37]
This Service Workers required disable uMatrix.

**Comment by chrisdavidmills** [comment]
I'm not sure what uMatrix requires, but it still seems to work fine for me. Are you running our test version at https://mdn.github.io/sw-test/ ?

**Comment by MESWEB** [comment]
Yes I was use couple of service agent script and always script has been blocked by UMatrix. I found solution by disable this extension. Second thing when script has been working then didn't download required scripts from stream like bootstrap etc.

**Comment by chrisdavidmills** [comment]
Ah right, so we can close this then.
