### ISSUE TITLE
Service Worker working on HTTP/1.1

### ISSUE THREAD

**Issue by MESWEB** [mdn/sw-test#38]
My server and domain use HTTP/2 but after implement Service Worker serving site by protocol HTTP/1.1
Is any way to change it?

**Comment by NostraDavid** [comment]
I've noticed too that files that have been cached on my Service Worker are served via HTTP/1.1, but I don't think that matters, since they're all cached locally anyway.

**Comment by MESWEB** [comment]
This bug exist more than 2 years and it's still alive:
https://bugs.chromium.org/p/chromium/issues/detail?id=872776

**Comment by schalkneethling** [comment]
The status of the above bug has been marked as resolved.
