### ISSUE TITLE
last update seems broken

### ISSUE THREAD

**Issue by patrickkettner** [mdn/sw-test#6]
I think the [last commit](301c3f0ae79c415e31d0e81ae3b4942b5eb74520) broke the example - [in the sw.js file](https://github.com/mdn/sw-test/blob/301c3f0ae79c415e31d0e81ae3b4942b5eb74520/sw.js#L21-L31), where is `event` supposed to come from? Shouldn't that be inside of a on('fetch')?

**Comment by chrisdavidmills** [comment]
Argh, I'm an idiot - it should be fixed now...thanks!
