### ISSUE TITLE
For `caches.match` Chrome resolves with undefined, seems, not rejects the promise...

### ISSUE THREAD

**Issue by Yaffle** [mdn/sw-test#8]
But your code and the docs at
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Recovering_failed_requests
says that `caches.match` is rejected.

**Comment by jonpacker** [comment]
I ran into this as well, super confusing.

**Comment by noopole** [comment]
This will work (on Chrome):

    event.respondWith( caches.match( event.request ).then( function ( resp ) 
    {
        if ( resp )
            return resp
        else
            return fetch( event.request ).then( function ( r ) 
            {
                response = r
                caches.open( 'v1' ).then( function ( cache ) 
                {
                    cache.put( event.request, response )
                } )
                return response.clone()
            } )
        }
    } ).catch( function ( err ) 
    {
        console.warn( err )
    } ) )

**Comment by chrisdavidmills** [comment]
I've fixed the incorrect information in the "Using..." article. Sorry about that!
